name: Build Geode Mod

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Windows
            os: windows-2022
          - name: Android 32-bit
            os: ubuntu-22.04
            target: Android32
          - name: Android 64-bit
            os: ubuntu-22.04
            target: Android64

    name: Compile for ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4

      # Explicitní instalace Geode CLI (pro jistotu!)
      - name: Setup Geode
        uses: geode-sdk/setup-geode@main

      - name: Build mod
        uses: geode-sdk/build-geode-mod@main
        with:
          combine: true
          target: ${{ matrix.config.target }}
